### ISSUE TITLE
401: Unauthorized for statuses/filter.json error even after using appLogin

### ISSUE THREAD

**Issue by logesh2496** [PLhery/node-twitter-api-v2#105]
Am following this: https://github.com/PLhery/node-twitter-api-v2/blob/27fd130379d187f9c277a9c74ef4f425db01ffe5/doc/auth.md#application-only-authentification-flow to authorize the twitter client and start a filter streaming. But i get 401 error. Below is the code

`this.client = new TwitterApi({
      appKey: TWITTER_API_KEY,
      appSecret: TWITTER_KEY_SECRET,
      accessToken: TWITTER_ACCESS_TOKEN,
      accessSecret: TWITTER_TOKEN_SECRET,
    });
`
...
`this.twitterBearerToken = await this.client.appLogin();`
`this.stream = await this.twitterBearerToken.v1.filterStream({ follow: [this.userId] });`

**Comment by gilgardosh** [comment]
Hi,
I have the same issue as @logesh2496, the 401 - Unauthorized after a few hours.
Did you manage to workaround that?
