### ISSUE TITLE
Getting 403 with correct keys

### ISSUE THREAD

**Issue by Matt-Pilott** [PLhery/node-twitter-api-v2#106]
Hi i tried switching from twitter-v2 to this twitter-api-v2 package and i'm seeing a 403 when doing the following:

```js
import TwitterApi from 'twitter-api-v2'

const client = new TwitterApi({
   appKey: import.meta.env.VITE_CONSUMER_KEY,
   appSecret: import.meta.env.VITE_CONSUMER_SECRET,
   accessToken: import.meta.env.VITE_TOKEN_KEY,
   accessSecret: import.meta.env.VITE_TOKEN_SECRET,
})

const rwClient = client.readWrite
const user = await rwClient.v2.userByUsername('Matt_Pilott')
```

The env variables are there and correct, the first 2 are the API key and secret from consumer keys on twitter and the second 2 are generated in the developer portal as personal access token and secret, so should all be correct and works if i switch back to the twitter-v2 package

Where have i gone wrong here?

**Comment by alkihis** [comment]
Hi, what's the exact error that you can copy paste here?
The code seems correct, but a 403 can means many things on Twitter API.

**Comment by Matt-Pilott** [comment]
@alkihis this is what i get:

```bash
ApiResponseError: Request failed with code 403
    at RequestHandlerHelper.createResponseError (/Users/Matt/Sites/matter/node_modules/.pnpm/twitter-api-v2@1.6.5/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:70:16)
    at RequestHandlerHelper.onResponseEndHandler (/Users/Matt/Sites/matter/node_modules/.pnpm/twitter-api-v2@1.6.5/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:110:25)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1340:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  error: true,
  type: 'response',
  code: 403,
  headers: {
    'set-cookie': [
      'guest_id=v1%3A163621043944808239; Max-Age=63072000; Expires=Mon, 06 Nov 2023 14:53:59 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None'
    ],
    'content-type': 'application/problem+json',
    'cache-control': 'no-cache, no-store, max-age=0',
    'content-length': '325',
    'x-response-time': '100',
    'x-connection-hash': '96f2713f7466f0aae4d55403d2298b3b459db37e873fc0c62b45185d58b6fcbd',
    date: 'Sat, 06 Nov 2021 14:53:59 GMT',
    server: 'tsa_f',
    connection: 'close'
  },
  rateLimit: undefined,
  data: '{\n' +
    '  "title": "Unsupported Authentication",\n' +
    '  "detail": "Authenticating with Unknown is forbidden for this endpoint.  Supported authentication types are [OAuth 1.0a User Context, OAuth 2.0 Application-Only, OAuth 2.0 User Context].",\n' +
    '  "type": "https://api.twitter.com/2/problems/unsupported-authentication",\n' +
    '  "status": 403\n' +
    '}'
}
```

Here's where im generating keys btw
<img width="1799" alt="Screenshot 2021-11-06 at 2 56 06 pm" src="https://user-images.githubusercontent.com/2401925/140614004-515f3dac-d4c5-4f63-bc3a-7a63dc51eb6c.png">

**Comment by alkihis** [comment]
@Matt-Pilott It seems the request isn't authentificated at all.
Are you sure all your given tokens imported through `import.meta` yield `string`s?

It seems you use `pnpm` package manager, yet I haven't tested the lib with it (even though it doesn't change anything at all).
What's the result of `client.getActiveTokens()`? (Remember to falsify/strip your tokens from the result)

Sorry for the incovenience.

**Comment by Matt-Pilott** [comment]
You're going to laugh but i had a typo in my env file 🤦‍♂️

Thanks so much for your help though really appreciate it!
