### ISSUE TITLE
How to add user.field expansion?

### ISSUE THREAD

**Issue by gauloics** [PLhery/node-twitter-api-v2#113]
[Here](https://github.com/PLhery/node-twitter-api-v2/blob/568fea8903f6d1448b9f9a1c09a73bca7228ab8a/doc/v2.md#search-tweets-recent) expansion author_id work, but how to add user.field?

`const jsTweets = await client.v2.search('JavaScript', { 'expansions': ['author_id'] , 'user.fields='entities'});`
This return error

> ErrorRequest failed with code 400 - Invalid Request: One or more parameters to your request was invalid. (see https://api.twitter.com/2/problems/invalid-request)

**Comment by alkihis** [comment]
Hi, are you sure you've wrote this code correctly?

The correct writing is:
```ts
client.v2.search('JavaScript', { 'expansions': ['author_id'] , 'user.fields': ['entities'] })
```
