### ISSUE TITLE
v2 version for homeTimeline and accountSettings

### ISSUE THREAD

**Issue by tonka3000** [PLhery/node-twitter-api-v2#122]
Hi,

I've try to make my app v2 compatible but I run into some problems. I'm searching for v1.homeTimeline and v1.accountSettings in the v2 end point.

I wanna simply fetch the user feed (not all tweet from the specific user), like when you visit twitter.com.

I was also not able to receive the current authenticated user with v2 like it was possible with v1.accountSettings.

Do you have any hints for that cases?

Thanks in advance
Michael

**Comment by alkihis** [comment]
Hello :) 

The things you look for are not yet accessible in v2 API. This package only produce a "copy" of what's available in public Twitter API v2.
You can look what's available now [here](https://developer.twitter.com/en/docs/twitter-api/migrate/twitter-api-endpoint-map).

**Comment by tonka3000** [comment]
> The things you look for are not yet accessible in v2 API

I already checked the twitter docs, but could not believe that there are no replacement for such functionality.

> This package only produce a "copy" of what's available in public Twitter API v2.

Make sense :smile:

> You can look what's available now here.

Thanks for the link

Hopefully twitter will add these endpoint before v1 get dropped.
