### ISSUE TITLE
Where can I find "YOUR_APP_USER_TOKEN"?

### ISSUE THREAD

**Issue by lumenwrites** [PLhery/node-twitter-api-v2#126]
Hi there! I'm new to this, this is the first time I'm trying to use this library. Can you help me to figure out where I can find "YOUR_APP_USER_TOKEN"?

 I have copy-pasted the code from the README (with minor changes):
```javascript
import { TwitterApi } from 'twitter-api-v2'

// Instanciate with desired auth type (here's Bearer v2 auth)
const twitterClient = new TwitterApi(<YOUR_APP_USER_TOKEN>)

// Play with the built in methods
const user = await roClient.v2.userByUsername('plhery')
console.log('user', user)
const tweet = await twitterClient.v1.tweet('Hello, this is a test.')
console.log(tweet)
// You can upload media easily!
const image = await twitterClient.v1.uploadMedia('./format-your-writing-for-readability.jpg')
```

But I can't seem to figure out where to get the user token, the only keys I see in my developer portal are these:

![screencapture-developer-twitter-en-portal-projects-1470847515079630855-apps-22799089-keys-2021-12-15-14_39_13](https://user-images.githubusercontent.com/4761235/146206816-4ad1ab65-be4f-4702-884f-44d619079dcb.png)

Where can I get the user token? What's the easiest way to obtain it?

(My goal is to post tweets using this api, not just read data, I don't know if that matters.)

**Comment by alkihis** [comment]
Hi,

So, you're new to Twitter development? 😄 
You now have multiple authentication methods on this API.

- OAuth2 Bearer Token (shown on example here), is only for **app auth**. It means you can only **read content, not write anything**
- OAuth2 user-context, which are the things related to Client ID and Client Secret, but this has been released to public **yesterday** and implementation is still a WIP for this lib.
- OAuth 1.0a user-context token (the historical one), that allows you to post content, but you need to implement a three-legged OAuth flow (example described in Authentication documentation). 
  If you don't want to implement it right away, you can generate the 4-keys couple "API key", "API secret", "access token" and "access token secret" for **your account** in Twitter Developer portal and use it as it follows:
```ts
const client = new TwitterApi({ appKey: 'API key', appSecret: 'API secret', accessToken: 'Access token', accessSecret: 'Access token secret' });
```
Don't forget to generate them with **read and write permissions**.

If you want to implement a login flow "a sign in with Twitter flow", I highly recommend you to read [Twitter documentation](https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens) and [library doc about auth](https://github.com/PLhery/node-twitter-api-v2/blob/feat/oauth2-user-out-of-beta/doc/auth.md#user-wide-authentication-flow).

**Comment by lumenwrites** [comment]
Thank you SO much for your help! This is incredible! It works, and I can send tweets! I'm **very** happy, you've made my day!

One more question if you don't mind.

I'm trying to complete the OAuth 1.0a three-legged flow, and I think it basically works. When the user returns to the url I'm using the secret keys to obtain the permanent keys, as in the example app:
```
      // Build a temporary client to get access token
      const tempClient = new TwitterApi({
        appKey: process.env.TWITTER_APP_KEY,
        appSecret: process.env.TWITTER_APP_SECRET,
        accessToken: oauth_token,
        accessSecret: savedSecret
      })

      // Ask for definitive access token
      const user = await tempClient.login(oauth_verifier)
```

This gives me the variables `accessToken, accessSecret, screenName, userId `, which is pretty cool. But for some reason, I don't see the user's twitter username or email anywhere on the object, even though I checked "Request email from users (optional)" in the OAuth setting in the developer dashboard.

Can you help me to figure out how to use your library to fetch the user's email and twitter username?

**Comment by lumenwrites** [comment]
Oh, sorry, and one more question.

I want to be able to ask the user to authorize my app when they sign up for the first time (with `const authLink = await client.generateAuthLink(CALLBACK_URL, { linkMode: 'authorize' })`), but then when the user tries to log in after that, I just want to log them in, without requiring them to click "authorize" again.

That's how it seems to work in Hypefury app. When you try to [login](https://app.hypefury.com/login) for the first time, it takes you to "Authorize" page. You click authorize, it signs you up. If you log out and then try to login again, it takes you to twitter but there's no "Authorize" button, it just immediately sends you back to the app.

Do you by any chance know how this works? How can I know whether to use `{ linkMode: 'authorize' }` (when the user signs up for the first time) or not, before the user has logged in?

**Comment by alkihis** [comment]
Very happy that you've managed to handle auth flow!

**For your first question**, yep, Twitter only returns **basic information after a successful login flow**.
If you want more data, you'll need to get full user object.

- If you have access to v1 API:
```ts
const user = await client.currentUser();
console.log(user.name)
```
=> [reference](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials)

- If you only have access to v2 API, you can use the brand new `users/me` endpoints (that is not typed yet):
```ts
const { data: user } = await client.v2.get('users/me');
console.log(user.name)  
```
=> [reference](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-me)

--- 

**For your second question**, my advise is to always use `authenticate` link mode all the time. It doesn't matter if the user already accepted the app or not. If he hasn't, he will be prompted to do so; if it's already done, it will just be a redirection without any approbation.

Only use `authorize` if you want to force user to give approbation each time he wants to connect (which isn't what you want to do)

**Comment by lumenwrites** [comment]
Thank you! The second question is resolved, just always using `authenticate` works, that's exactly what I want (for some reason I initially assumed that you have to first authorize and only then use authenticate, but when you just use authenticate it prompts the user to authorize the app if they didn't before).

I'm still struggling to obtain the user's email address though.

I've tried both:
```
const user = await client.currentUser();
console.log(user)
```
and
```
const { data: user } = await client.v2.get('users/me');
console.log(user)  
```

And it returns a lot of info about the user, but no email. 

I see that the first [link](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials) you gave me mentions returning the email if "Request email addresses from users" is checked, and I did check it, but I still don't see the email in the response. I don't think I'm using this correctly...

Can you help me to figure out how to obtain the email?
