### ISSUE TITLE
How do I access the v1 search?

### ISSUE THREAD

**Issue by weirdyang** [PLhery/node-twitter-api-v2#135]
I wish to use the search by passing a query, 

https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets

I intend to find all the user's tweets in the past year, and from what I can tell, this will be more efficient. How do I go about doing so?

![Capture](https://user-images.githubusercontent.com/25576022/147401369-71467ac8-9de2-4830-92ae-6eaed2eb848b.PNG)

I've also tried using v2 search, but I get  `Error: Request failed with code 403 - Your credentials do not allow access to this resource. (Twitter code 220)`, however my app has full permissions.

Please do let me know if I'm mistakened.

**Comment by alkihis** [comment]
Hi :)

API v2 endpoints are only available if your application is part of a project: [see here](https://developer.twitter.com/en/docs/projects/overview). This can be the reason of why you can't use the v2 endpoint.

Or you're using only consumer tokens (without access tokens) to log in. In this can you need yo use your Bearer token (available on the same page).

> I intend to find all the user's tweets in the past year, and from what I can tell, this will be more efficient. How do I go about doing so?
**Answer**: You simply can't! As you can read in the documentation, search is limited to **7 days ago**.

---

Still, here's how you can use search v1 endpoint:

v1 search isn't implemented through an endpoint wrapper, you need to call it by yourself:
```ts
import TwitterApi, { TweetV1 } from 'twitter-api-v2' 

interface SearchV1Result {
  statuses: TweetV1[]
  search_metadata: { max_id_str: string; since_id_str: string; count: number; next_results?: string; }
}

const tweets = await client.v1.get<SearchV1Result>('search/tweets.json', { q: 'from:alkihis' })

console.log(tweets.statuses)
```

**Comment by weirdyang** [comment]
Thanks. Ended up doing it mainly using regular request and oauth.
Appreciate the clarification

**Comment by flolege** [comment]
How would I do that in pure javascript?
