### ISSUE TITLE
ApiRequestError crashing program

### ISSUE THREAD

**Issue by Crucial288** [PLhery/node-twitter-api-v2#137]
I am not 100% sure if this is an issue with the library or not, but I'm hoping maybe you can help me shed on light on this.
I am making two calls using the v1 api - uploadMedia, and tweet. This can work fine for hours, but occasionally and fairly reliably, my entire application will crash when the library returns 
`return new types_1.ApiRequestError('Request failed.', {`

The code for both of these methods is wrapped in try catch in the application, which doesn't seem to stop it from crashing, and the error message returned doesn't have any more information.

Would love any advice on this!

**Comment by alkihis** [comment]
Hello, sorry for the long delay :smiling_face_with_tear: 

I will try to reproduce this problem (maybe a network error?), but I've never ran over it before :sweat_smile:

**Comment by Crucial288** [comment]
`<Project Directory>\node_modules\twitter-api-v2\dist\client-mixins\request-handler.helper.js:41
        return new types_1.ApiRequestError('Request failed.', {
               ^
ApiRequestError: Request failed.
    at RequestHandlerHelper.createRequestError (<Project Directory>\node_modules\twitter-api-v2\dist\client-mixins\request-handler.helper.js:41:16)
    at RequestHandlerHelper.requestErrorHandler (<Project Directory>\node_modules\twitter-api-v2\dist\client-mixins\request-handler.helper.js:97:21)
    at ClientRequest.emit (node:events:394:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {    
  error: true,
  type: 'request'
}
[nodemon] app crashed - waiting for file changes before starting...`


I tried to look through the code but it doesnt seem like theres anything that's easy to point out to. I can say for sure the uploadMedia request always fails the same way and first,

What doesn't exactly make sense to me is the fact that it's crashing the entire program - is it some kind of memory leak?

**Comment by alkihis** [comment]
I don't think they're is some memory leak here - I've tested by manually triggering a request error in a `try-catch` structure in a `.uploadMedia` context, everything just goes fine.

I've tested on MacOS + Node 14, and Linux + Node 16. What's your personal environnement?

Unfortunately, the stack trace doesn't help me more... If the problem still goes on, I will need more context, like a code example.

You can also enable debug logging to trace all requests to console:
```ts
import { TwitterApiV2Settings } from 'twitter-api-v2';

TwitterApiV2Settings.debug = true;
```

**Comment by alkihis** [comment]
I suppose problem is solved? I wasn’t able to reproduce it and no one reported it except you. I close the issue, reopen it if you need to.
