### ISSUE TITLE
Deno version?

### ISSUE THREAD

**Issue by jchannon** [PLhery/node-twitter-api-v2#158]
Ever thought or making it work with Deno?

**Comment by alkihis** [comment]
Deno makes request handling completely differently and use different internal modules.
So unless they're is a fork adapted specifically for Deno, this isn't possible.

**Comment by jchannon** [comment]
I have forked it and begun work but I'm new to Deno and Typescript and this
codebase so it's a bit confusing for me to understand what the current code
base is doing with promises for requests etc.

I'd be happy to get all the imports and adapt some of the types to Deno
types working if you'd be interested in helping out?

**Comment by alkihis** [comment]
Sorry, this isn't planned for me and I haven't the time to work on it.
Moreover, this lib abusely use native `http` node module implementation, that is event based. 
In Deno, requests are Promise-base, so code related to request handling is to re-think completely.

**Comment by jchannon** [comment]
ok thanks!
