### ISSUE TITLE
Unable to resolve module events from error?

### ISSUE THREAD

**Issue by jesuasir007** [PLhery/node-twitter-api-v2#159]
/node_modules/twitter-api-v2/dist/stream/TweetStream.js: events could not be found within the project or in these directories:
  node_modules
  ../../../../node_modules
  
  how can I fix it.

**Comment by alkihis** [comment]
Do you use Node.js?
Or you're trying to use this on a client-side project?

**Comment by jesuasir007** [comment]
I have using react native

**Comment by jesuasir007** [comment]
> Do you use Node.js?
> Or you're trying to use this on a client-side project?

you can help about this topic?

**Comment by alkihis** [comment]
This lib is not meant to be used in non-Node.js projects.
Moreover, you should not make requests on client-side, because it will leak your private keys to the client.

Make a server that is a proxy between your app and Twitter, do not communicate with Twitter directly.
