### ISSUE TITLE
Minor errors in example codes

### ISSUE THREAD

**Issue by yukidaruma** [PLhery/node-twitter-api-v2#161]
There was minor error in example codes in TS comment.

Without supplying `clientSecret`, you will get error when calling `loginWithOAuth2` or `refreshOAuth2Token`.
**UPDATE**: I can confirm `revokeOAuth2Token` needs `clientSecret` to be supplied, too. However, `generateOAuth2AuthLink` looks like it does **NOT** require `clientSecret`.

```ts
// https://github.com/PLhery/node-twitter-api-v2/blob/9aa80d1f39a28c502899564011450b62021bf898/src/client/readonly.ts#L246-L254
// This didn't work
new TwitterApiV2({ clientId: 'yourClientId' })
      .loginWithOAuth2({ code, codeVerifier, redirectUri: CALLBACK_URL });

// This worked
new TwitterApiV2({ clientId: 'yourClientId', clientSecret: 'secret' })
      .loginWithOAuth2({ code, codeVerifier, redirectUri: CALLBACK_URL });
```

Probably occurrences of `new TwitterApi({ clientId: \'<yourClientId>\' })'` in error messages need to be updated too, for example, codes like below:
```ts
// https://github.com/PLhery/node-twitter-api-v2/blob/9aa80d1f39a28c502899564011450b62021bf898/src/client/readonly.ts#L262-L265
      throw new Error(
        'Twitter API instance is not initialized with client ID. ' +
        'Please build an instance with: new TwitterApi({ clientId: \'<yourClientId>\' })',
      );
```

By the way, documentations below didn't have these errors.
- https://github.com/PLhery/node-twitter-api-v2/blob/9aa80d1f39a28c502899564011450b62021bf898/doc/auth.md?plain=1#L229
- https://github.com/PLhery/node-twitter-api-v2/blob/9aa80d1f39a28c502899564011450b62021bf898/doc/auth.md?plain=1#L257

**Comment by alkihis** [comment]
Hi,
This isn't an issue!
Client secret is mandatory only if your application is qualified as "private" in the developer portal.
Otherwise, only a client ID is needed.

In a Node.js context, we except that the app is considered to be private (that's why documentation only mention usage with client secret every time), but it is purely optional and user-customizable.

**Comment by yukidaruma** [comment]
@alkihis Hi, thank you for the quick response. It makes a lot of sense.
It looks like you need to supply client secret only when the app is classified as "confidential clients".
<img width="300" src="https://user-images.githubusercontent.com/6897821/149646726-99785e5e-6437-4e0f-91c7-a8d2d36cd938.png">

I'm closing this issue.
