### ISSUE TITLE
Trouble understanding authentication of a bot via bearer token

### ISSUE THREAD

**Issue by Schepp** [PLhery/node-twitter-api-v2#162]
Hey there,

I'd like to use this package to search for certain tweets on Twitter. Reading the docs I though it might be easiest to use a bearer token as authentication method, as the Twitter Developer dashboard already created one for my app 👇🏻

![image](https://user-images.githubusercontent.com/135141/149660382-292cbb84-ab69-41e0-9684-f78d857bf36f.png)

So I went with this code to begin with:

```js
const {
  TwitterApi,
  TwitterApiV2Settings
} = require('twitter-api-v2');

TwitterApiV2Settings.debug = true;

// OAuth2 (app-only or user context)
// Create a client with an already known bearer token
const client = new TwitterApi('AAAAAAAAA...');

const fetch = async () => {
  try {
    const jsTweets = await client.readOnly.v2.searchAll('JavaScript', {'media.fields': 'url'});

    // Consume fetched tweet from first page of jsTweets
    for (const tweet of jsTweets) {
      console.log(tweet);
    }

    return jsTweets;
  } catch(e) {
    console.error(e);
  }
}

fetch();
``` 

Sadly, all I get is this error message:

```
 data: {
    client_id: 'xxx',
    detail: 'When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.',
    registration_url: 'https://developer.twitter.com/en/docs/projects/overview',
    title: 'Client Forbidden',
    required_enrollment: 'Standard Basic',
    reason: 'client-not-enrolled',
    type: 'https://api.twitter.com/2/problems/client-forbidden'
  }
```

This isn't a very helpful reply from Twitter. 

Where do I miss something? Thank you in advance for any kind of help/hint 🙏

**Comment by Schepp** [comment]
Okay, it seems that the API V2 search needs more elevated levels to be granted by Twitter.

**Comment by rodrigograca31** [comment]
> Okay, it seems that the API V2 search needs more elevated levels to be granted by Twitter.

what do you mean? paying? or contacting them to "elevate" your app? 🤔
