### ISSUE TITLE
I have face this issues when run, how can I fix it ?

### ISSUE THREAD

**Issue by jesuasir007** [PLhery/node-twitter-api-v2#166]
Unable to resolve module fs from /Users/macminim1/Desktop/ProjectS2022React/Project/tweetomatic/node_modules/twitter-api-v2/dist/v1/client.v1.write.js: fs could not be found within the project or in these directories:
  node_modules
  ../../../../node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
[0m [90m 25 |[39m [36mconst[39m globals_1 [33m=[39m require([32m"../globals"[39m)[33m;[39m[0m
[0m [90m 26 |[39m [36mconst[39m client_v1_read_1 [33m=[39m __importDefault(require([32m"./client.v1.read"[39m))[33m;[39m[0m
[0m[31m[1m>[22m[39m[90m 27 |[39m [36mconst[39m fs [33m=[39m __importStar(require([32m"fs"[39m))[33m;[39m[0m
[0m [90m    |[39m                                  [31m[1m^[22m[39m[0m
[0m [90m 28 |[39m [36mconst[39m media_helpers_v1_1 [33m=[39m require([32m"./media-helpers.v1"[39m)[33m;[39m[0m
[0m [90m 29 |[39m [36mconst[39m helpers_1 [33m=[39m require([32m"../helpers"[39m)[33m;[39m[0m
[0m [90m 30 |[39m [36mconst[39m [33mUPLOAD_ENDPOINT[39m [33m=[39m [32m'media/upload.json'[39m[33m;[39m[0m

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
RunCurrentEventLoopInMode
ReceiveNextEventCommon
_BlockUntilNextEventMatchingListInModeWithFilter
_DPSNextEvent
-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
-[NSApplication run]
NSApplicationMain
main
start

**Comment by alkihis** [comment]
Hi,
A few days ago you've opened an issue from an import error for the `events` module.
I've told you this library only targets Node.js ; but you try to use it on React Native on iOS, if I understand the stack trace well.
Now you open another issue for the module `fs`: `"fs could not be found"`

Both [events module](https://nodejs.org/api/events.html) and [fs module](https://nodejs.org/api/fs.html) are from Node internals.
Unfortunately, I cannot help you with it, as your framework forbid to use them.
