### ISSUE TITLE
Upload media returns 403

### ISSUE THREAD

**Issue by myin142** [PLhery/node-twitter-api-v2#167]
When I try to upload a media with this library I get a 403 forbidden error.

I am using the OAuth 2.0 User Context as authentication so I think this shouldn't be a problem. I also tried it with OAuth 1.0 User Context just in case. Also didn't work.
Other endpoints like tweeting and getting user information works without problems.
My app should also have elevated access so that shouldn't be it either.

It could be that the problem is that twitter changed all requests to use SSL/HTTPS since 2021-01-14. Was this library tested to work with the new changes? Other than that I don't really know what the problem could be.

**Comment by dvtate** [comment]
I'm having the same issue except it's also giving me problems with replies

**Comment by alkihis** [comment]
Hi,
OAuth2 user-context does not allow to use v1 API. So, you cannot use `media/upload` with it.

OAuth 1.0a + media upload works fine and is fully unit-tested ([see here](https://github.com/PLhery/node-twitter-api-v2/blob/master/test/media-upload.test.ts)). Maybe you're using an invalid file or you have incorrect parameters?

You can paste a code sample + response data (catch error and print `error.data`) to help me more than that.

> It could be that the problem is that twitter changed all requests to use SSL/HTTPS since 2021-01-14.

This is has been *mostly* built after this date. 100% of requests are made through HTTPS since day one :)

**Comment by myin142** [comment]
Sorry about the SSL/HTTPS. First I wrote the wrong date, still used to using the last year but I forgot to check the date of the post where I read it. It was posted a long time ago :sweat_smile: 

For the sample code: this is for authentication. I don't think that there are any problems here since the user call works fine. `clientId` and `clientSecret` is the correct appKey and the appSecret. I just didn't want to rename them back because I want to keep using OAuth2 in the future. And assume the result of `getLoginUrl` is getting called by the user and correctly redirected back. Basically assume the auth workflow works fine without errors :)
```typescript
export class TwitterAuthService implements SNSAuthService {
  constructor(private options: OAuthOptions) {}

  private get client() {
    const { clientId, clientSecret } = this.options;
    return new TwitterApi({
      appKey: clientId,
      appSecret: clientSecret,
    });
  }

  async getLoginUrl(
    redirect: string,
    scope: string[] = []
  ): Promise<OAuthLogin> {
    const { url, oauth_token_secret } = await this.client.generateAuthLink(
      redirect
    );

    return { url, state: oauth_token_secret };
  }

  async handleCallback({
    oauth_token,
    oauth_verifier,
    originalState: secret,
  }: TwitterOAuthCallback): Promise<OAuthCallbackResponse> {
    if (!oauth_token || !oauth_verifier || !secret) {
      throw new Error('You denied the app or your session expired');
    }

    const { clientId, clientSecret } = this.options;

    const client = new TwitterApi({
      appKey: clientId,
      appSecret: clientSecret,
      accessToken: oauth_token,
      accessSecret: secret,
    });

    const { accessToken, accessSecret } = await client.login(oauth_verifier);
    return { token: `${accessToken};${accessSecret}` };
  }
}

```

And I am just calling it with the upload function: `accessToken` and `secret` are the ones returned from the previous callback function.
```typescript
    // Somewhere in the class
    this.client = new TwitterApi({
      appKey: clientId,
      appSecret: clientSecret,
      accessToken: accessToken,
      accessSecret: secret,
    });

  // A method in the class
  async uploadImage(file: Buffer, filename: string): Promise<string> {
    return await this.client.v1.uploadMedia(file, {
      type: filename.split('.')[1],
    });
  }
```

The error doesn't seem helpful but here it is:
```
Error: Request failed with code 403
    at RequestHandlerHelper.createResponseError (/home/sakkaku/Documents/kumi-arts/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:71:16)
    at RequestHandlerHelper.onResponseEndHandler (/home/sakkaku/Documents/kumi-arts/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:111:25)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by myin142** [comment]
Sorry forgot about catching the error:
```
ApiResponseError: Request failed with code 403
     at RequestHandlerHelper.createResponseError (/home/sakkaku/Documents/kumi-arts/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:71:16)
     at RequestHandlerHelper.onResponseEndHandler (/home/sakkaku/Documents/kumi-arts/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:111:25)
     at IncomingMessage.emit (node:events:402:35)
     at endReadableNT (node:internal/streams/readable:1343:12)
     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
   error: true,
   type: 'response',
   code: 403,
   headers: {
     'cache-control': 'no-cache, no-store, max-age=0',
     'content-length': '0',
     'x-response-time': '115',
     'x-connection-hash': 'b7d33cf8a26ae034e3dbb117563b65d1998300b8b65d3388c20761745cf5c224',
     date: 'Mon, 24 Jan 2022 16:47:34 GMT',
     server: 'tsa_o',
     connection: 'close'
   },
   rateLimit: undefined,
   data: ''
 }
```

**Comment by alkihis** [comment]
Hello again, sorry for the delay.

Auth flow seems good to me, no problem; if you can post tweets, it's totally sure that your configuration works.
It is really weird that Twitter doesn't respond with anything... `data` property of error seems empty.

Your `Buffer` can contain an invalid image, but Twitter should reply with a `400`, not `403`.

---

Can you please enable [debug mode](https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/errors.md#debug-your-requests) and paste the result here of the failing request? (request **and** response)

Be careful, your OAuth consumer keys will appear in headers, be sure to remove them.

**Comment by myin142** [comment]
Sorry for the trouble. It was a mistake on my side. After changing to OAuth 1.0a, I didn't enable it in the developer settings so I only had read-only access.

**Comment by arantespp** [comment]
If someone also has this issue about OAuth 1.0a permission, follow [this step by step](https://twittercommunity.com/t/how-do-i-change-my-app-from-read-only-to-read-write/163624/4) to active read-write permissions.
