### ISSUE TITLE
client.v2.like() returns 403

### ISSUE THREAD

**Issue by thathurtabit** [PLhery/node-twitter-api-v2#178]
Hi, I've been using `node-twitter-api-v2` for the last week and has been working well 👍 
But I'm currently running into a `403` error when trying to use `await client.v2.like(myTwitterID, tweetID)`

All arguments passed into the method are valid, and I'm using `myTwitterID` and this `tweetID` successfully in another method, but doesn't seem to work with `await client.v2.like(myTwitterID, tweetID)`;

I hope I'm missing something obvious!

Docs here:
https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/v2.md#Likeatweet

**Comment by alkihis** [comment]
Hi!

I've quickly checked on my side, and it should work with those parameters.

I've two questions for you:
- What's the content of the error?
Catch the error, and get `e.toJSON()`:

```ts
try { 
  await client.v2.like(...) 
} catch (e) { 
  console.log(e.toJSON().error) 
}
```

- What's your authentification method? 
  - OAuth 1.0, OAuth2 (app-token), OAuth2 (user-context)?
  - If it's OAuth 1.0, are your sure your app have read/write permissions on the developer portal?
  - If it's OAuth2 with user-context, what's the token scope you've attributed?

**Comment by thathurtabit** [comment]
Thanks @alkihis. Turns out _of course_ I was being an idiot and was just missing the `"like.write"` scope permissions from the Twitter client. I added `like.write`, then re-authorised by app and everything works perfectly 👍  thank you for your help (I shouldn't try to code at 11pm).
