### ISSUE TITLE
No profile_image_url in includes.users - twitter-api-v2 

### ISSUE THREAD

**Issue by havana7** [PLhery/node-twitter-api-v2#181]
` const tweetOfId20 = await roClient.v2.singleTweet(TweetId, {
              expansions: [
                'author_id',                
                'entities.mentions.username',
                'in_reply_to_user_id',
                'referenced_tweets.id',
                'referenced_tweets.id.author_id'
              ],
            });`

The response includes Id, Name and Username but no profile_image_url

**Comment by alkihis** [comment]
Please how the [expansions](https://developer.twitter.com/en/docs/twitter-api/expansions) for [this endpoint](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets-id) works.

You need to add `'user.fields': ['profile_image_url']` to get this property.
