### ISSUE TITLE
Right type of authentication

### ISSUE THREAD

**Issue by valex91** [PLhery/node-twitter-api-v2#182]
Hello,
Thank for this amazing library, I love the type safety, but I'm struggling to understand what is the correct authentication that I need to use following the docs. I'm building a bot that can tweet and reply to tweet, but formally there is no front-end for re-direction for the classic auth0 flow that gets you authenticated and redirect to the app.

so far my login is

```
const tweetInstance = new TwitterApi({appKey: process.env.TWITTER_API_KEY!, appSecret: process.env.TWITTER_API_KEY_SECRET!});

        const twittClient = await tweetInstance.appLogin();
```
and for read-only works like a charm, but when I try to tweet I get this error:
```
"detail": "Authenticating with OAuth 2.0 Application-Only is forbidden for this endpoint.  Supported authentication types are [OAuth 1.0a User Context, OAuth 2.0 User Context].",\n' +
    '  "type": "https://api.twitter.com/2/problems/unsupported-authentication",\n' +
    '  "status": 403\n'
```

any pointers? Sorry Auth are not my strong suite.

Regards.

**Comment by alkihis** [comment]
- For OAuth 1.0a login method (v1 & v2 API)

Go to project app overview, on your app click on "keys and tokens"
<img width="200" alt="Capture d’écran 2022-02-11 à 14 05 29" src="https://user-images.githubusercontent.com/32335180/153596523-14885984-e360-4131-b183-0e0e69fec5a4.png">

Get your consumer keys "appKey" and "appSecret" here: <img width="824" alt="Capture d’écran 2022-02-11 à 14 06 17" src="https://user-images.githubusercontent.com/32335180/153596591-3e216db0-b84f-4d83-bae5-4398ebb139bb.png"> (click to regenerate, yes, and it will be shown)

Get your access tokens "accessToken" and "accessSecret" here, same as consumer keys, regenerate and add them in your project
<img width="850" alt="Capture d’écran 2022-02-11 à 14 07 29" src="https://user-images.githubusercontent.com/32335180/153596763-552b3d89-efe5-4abd-b4d3-6499b2648e8e.png">

Be careful to select Read/Write permissions.
 
- For OAuth2 user-context (v2 only)

You need to generate them by yourself with a login flow. No other method.

**Comment by alkihis** [comment]
If you've another problem with Twitter API, you can open a new discussion in the "GitHub Discussion" feature :) 
It is meant to be a place to ask general help about Twitter API!

**Comment by npomfret** [comment]
@valex91 did you solve this?
