### ISSUE TITLE
[bug] Scope in OAuth2.0 requires percent encoding

### ISSUE THREAD

**Issue by Aquilae00** [PLhery/node-twitter-api-v2#184]
`client.generateOAuth2AuthLink(...)` function generates url with scope `scope=tweet.read+users.read+offline.access` which doesn't have percent encoding.

This url returns HTTP 400 as mentioned in  https://twittercommunity.com/t/http-400-with-redirect-is-requested-error-description-from-oauth2-authorize-endpoint/164764/14

Based on Twitter's doc, https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code
Scope requires percent encoding.

> You will need to have the proper encoding for this URL to work, be sure to check out our documentation on the [percent encoding](https://developer.twitter.com/en/docs/authentication/oauth-1-0a/percent-encoding-parameters).

**Comment by alkihis** [comment]
Hi,

Thank you for your report. You're right, I missed that because opening the link in Chrome automatically fixes the issue.
This will be fixed soon :)
