### ISSUE TITLE
Can't unfollow users! [bug]

### ISSUE THREAD

**Issue by Hannes1** [PLhery/node-twitter-api-v2#211]
**Describe the bug**
Hi, so I only want to unfollow users on my own twitter account but I keep getting a 403 forbidden.

```
ApiResponseError: Request failed with code 403
    at RequestHandlerHelper.createResponseError (C:\Hannes\twitter-api\node_modules\twitter-api-v2\dist\client-mixins\request-handler.helper.js:99:16)
    at RequestHandlerHelper.onResponseEndHandler (C:\Hannes\twitter-api\node_modules\twitter-api-v2\dist\client-mixins\request-handler.helper.js:227:25)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  error: true,
  type: 'response',
  code: 403,
  headers: {
    'content-type': 'application/problem+json',
    'cache-control': 'no-cache, no-store, max-age=0',
    'content-length': '316',
    'x-response-time': '101',
    'x-connection-hash': 'a3eedc4c11b8f6d5c8661336dfa45293f672ce7472794733705fce4c8e3dd1af',
    date: 'Wed, 02 Mar 2022 19:20:24 GMT',
    server: 'tsa_f',
    via: '1.1 google',
    'alt-svc': 'clear',
    connection: 'close'
  },
  rateLimit: undefined,
  data: '{\n' +
    '  "title": "Unsupported Authentication",\n' +
    '  "detail": "Authenticating with OAuth 2.0 Application-Only is forbidden for this endpoint.  Supported authentication types are [OAuth 1.0a User Context, OAuth 2.0 User Context].",\n' +
    '  "type": "https://api.twitter.com/2/problems/unsupported-authentication",\n' +
    '  "status": 403\n' +
    '}'
}
```

**To Reproduce**

    const twitterClient = new TwitterApi({
      appKey: process.env.TWITTER_API_KEY,
      appSecret: process.env.TWITTER_API_SECRET,
      accessToken: process.env.TWITTER_ACCESS_TOKEN,
      accessSecret: process.env.TWITTER_ACCESS_TOKEN_SECRET,
    });

    const user = await (await twitterClient.currentUserV2()).data;
    console.log(user); //I'm logged in and everything
    let result = await twitterClient.v2
      .unfollow(user.id, "737251813")
      .catch((err) => {
        console.log(err);
      }); //Getting 403

**Expected behavior**
Unfollow the user on my account

**Version**
 - Node.js version 14
 - Lib version 1.11.0
 - OS windows

**Comment by Hannes1** [comment]
Read and write🤔

**Comment by alkihis** [comment]
Update: after seeing again your response data, Twitter says you're logged with an application token only. 🤔
Are you sure you're using the same client between the two requests (currentUser and unfollow)?

**Comment by deadcoder0904** [comment]
this is the same error i get as well, see [my comment here](https://github.com/PLhery/node-twitter-api-v2/discussions/208#discussioncomment-2292816).

**Comment by deadcoder0904** [comment]
see my development app is the one i'm using:

![dev](https://user-images.githubusercontent.com/16436270/156706588-47051a2c-937a-47c7-83a5-499b79f47e08.png)

& it's a web app with confidential client:

![project](https://user-images.githubusercontent.com/16436270/156706825-8ff151c5-818d-4a8f-9579-ed95da6b37e4.png)

**Comment by alkihis** [comment]
This isn't related at all. It's not because you both have a 403 error means your problem are related 😅

Plus, you don't even use the same authentication method. And the error body isn't the same.

**Comment by deadcoder0904** [comment]
oh yes, his error is probably:

```bash
  data: '{\n' +
    '  "title": "Unsupported Authentication",\n' +
    '  "detail": "Authenticating with OAuth 2.0 Application-Only is forbidden for this endpoint.  Supported authentication types are [OAuth 1.0a User Context, OAuth 2.0 User Context].",\n' +
    '  "type": "https://api.twitter.com/2/problems/unsupported-authentication",\n' +
    '  "status": 403\n' +
    '}'
```

looks like he selected the wrong oauth method:

> Authenticating with OAuth 2.0 Application-Only is forbidden for this endpoint.  Supported authentication types are [OAuth 1.0a User Context, OAuth 2.0 User Context].

or callback isn't correct.

**Comment by Hannes1** [comment]
Got It working !

**Comment by deadcoder0904** [comment]
@Hannes1 what was the issue?

**Comment by Hannes1** [comment]
> @Hannes1 what was the issue?

Hi, Probable because I forgot to enable auth 2 in the developer portal lol

```
// I just get the accessToken either from TwitterApi or in my next project from NextAuthjs
    const userClient = new TwitterApi(accessToken);

    let result = await userClient.v2
      .unfollow(user.id, "737251813")
      .catch((err) => {
        console.log(err);
      });
```
