### ISSUE TITLE
Fetching Tweets from list forbidden with accesstoken[bug] 

### ISSUE THREAD

**Issue by Hannes1** [PLhery/node-twitter-api-v2#224]
**Describe the bug**
Hi, so using the user oauth2 access token works everywhere except for fetching list tweets where I get 403 Forbidden (And yes I use the v2 API everywhere and the token is still valid).
But it's weird as soon as I use the bearer token it works.

**To Reproduce**
```
  const client = new TwitterApi(process.env.BEARER_TOKEN); ----> Works
  const client = new TwitterApi(accessToken); ----> 403 Forbidden
    const tweets = await client.v2.listTweets(listId, {
      "tweet.fields": [
        "created_at",
        "id",
        "lang",
        "public_metrics",
        "possibly_sensitive",
        "text",
        "context_annotations",
      ],
      expansions: ["author_id"],
      "user.fields": ["name", "profile_image_url"],
      max_results: 50,
    });
```

**Expected behavior**
Get a list of tweets from a list

**Version**
 - Node.js 14
 - Lib latest
 - OS  Windows

Maybe I'm just being dumb

**Comment by alkihis** [comment]
Hi, what's the scope associated with your access token?

**Comment by Hannes1** [comment]
@alkihis thanks for helping this idiot. Didn't add list.read to scope
