### ISSUE TITLE
[bug] meta isn't properly typed

### ISSUE THREAD

**Issue by nicholaschiang** [PLhery/node-twitter-api-v2#231]
**Describe the bug**

The `res.meta` object returned by, for example, `api.v2.listTweets` isn't properly typed:

![image](https://user-images.githubusercontent.com/20798889/159535346-3b2cf328-9028-472a-ab31-9d0f5509a6e4.png)

**To Reproduce**
Please indicate all steps that lead to this bug:
1. Try to access `res.meta` when using Typescript.
2. See Typescript error.

**Expected behavior**

The `res.meta` object should be properly typed so that I can safely access the `next_token` and `previous_token` (to store them in a shared Redis cache that is referenced by all serverless function invocations).

**Version**
 - Node.js version: 16.14.0
 - Lib version: 1.11.1
 - OS (especially if you use Windows): Ubuntu 20.04 LTS

**Additional context**

**Comment by alkihis** [comment]
Hello,
This isn't a TypeScript **error**, this is just a property with a `any` typing.

But you're right, it is a typing mistake.

**Comment by alkihis** [comment]
Fixed on `master` branch :)
I will be fixed when 1.11.2 is out, but awaiting #229 to be clarified before pushing to npm.

**Comment by alkihis** [comment]
Now available on 1.11.2 😄
