### ISSUE TITLE
[feature] Implement january-march Twitter API v2 improvements

### ISSUE THREAD

**Issue by alkihis** [PLhery/node-twitter-api-v2#237]
- New spaces features: `topic_ids` and `ended_at` on space object, `/spaces/:id/buyers` endpoint
https://twittercommunity.com/t/adding-new-functionality-to-spaces-endpoints/161959

- `sort_order` parameter for tweet search endpoints
https://twittercommunity.com/t/introducing-the-sort-order-parameter-for-search-endpoints-in-the-twitter-api-v2/166377

- New bookmarks API
https://twittercommunity.com/t/build-with-bookmarks-on-the-twitter-api-v2/168804

- New Quoted tweets endpoint
https://developer.twitter.com/en/docs/twitter-api/tweets/quote-tweets/api-reference/get-tweets-id-quote_tweets

**Comment by darcy-vitacca** [comment]
Would love to see this implemented!

**Comment by nolbuzanis** [comment]
@alkihis If you split off 1-2 you're not working on and mark as a feature request, I'll take one of them!

**Comment by sartoshi-foot-dao** [comment]
@alkihis Thank you for the swift update. A bit surreal that Twitter has finally added Bookmarks API.
