### ISSUE TITLE
[bug] v2.search not returning extra requested parameteres

### ISSUE THREAD

**Issue by fetzsav** [PLhery/node-twitter-api-v2#275]
**Describe the bug**
v2.search(query, {'options': 'options'}) does not return the extra requested fields from the tweet

**To Reproduce**
I attempted with promise syntax and await/async syntax as according to the docs. Here is the code that I used:
`const twitter = new TwitterApi(auth);
 const tweetslist = await twitter.v2.search(searchQ, { 'user.fields': 'username' });
 for await (const tweet of tweetslist){
    console.log(tweet);
  }`
Only returns
{ 
id:
text:
}

**Expected behavior**
tweet to return 
{
id:
text:
username:
}

**Version**
 - Node.js version
 - 16.14
 - Lib version
 - 
 - OS (especially if you use Windows)
 - Ubuntu 20.04

**Additional context**

**Comment by alkihis** [comment]
Hello,
This is not a bug. Tweets cannot contain a field `username`, it's a field linked to user who have posted the tweet.
You must request it properly then fetch it using `response.includes`.

```ts
const search = await client.v2.search('12', { expansions: ['author_id'], 'user.fields': ['username'] })

for (const tweet of search) {
  const authorUser = search.includes.author(tweet)
  console.log(authorUser.username)
}
```

**Comment by simonbuehler** [comment]
hi,
i tried the helpers with the V2 stream, but to no avail, i wante to get the author username from a foudn tweet, any hint please?

```js
import { ETwitterStreamEvent, TweetStream, TwitterApi, ETwitterApiError, TwitterV2IncludesHelper } from 'twitter-api-v2';
const client = new TwitterApi('123'); // (create a client)
const stream = await client.v2.searchStream(  { expansions: ['author_id'], 'user.fields': ['username'] });
stream.on(
  ETwitterStreamEvent.Data,
  eventData =>  {
  //	const includes = new TwitterV2IncludesHelper(eventData)
	const authorUser = stream.includes.author(eventData)
        console.log(authorUser.username)
  //	console.log( JSON.stringify(includes.tweets));
  	console.log('Twitter has sent something:', JSON.stringify(eventData));
  },
);

// Enable reconnect feature
stream.autoReconnect = true;
```
