### ISSUE TITLE
Truncated tweet text

### ISSUE THREAD

**Issue by Flamenate** [PLhery/node-twitter-api-v2#276]
Hi, I was wondering if there's a way to get the full text from a TweetV2 object instead of the truncated text? I've read on Twitter docs that there is an "expandedTweet" field in the response that contains a "fullText" field with the non truncated version, but I don't see it in this library.
Thanks in advance.

**Comment by alkihis** [comment]
First, truncated tweet tweet (and expanded) does not exists in v2 API. Full text is always returned.
Secondly, even if you encounter this issue, this isn't related to the library itself. As it is specified in the issue template, the following issue will be closed.

**Comment by amosbastian** [comment]
@alkihis  I'm doing

```
const search = await client.v2.search(query, {
  "tweet.fields": ["text", "author_id", "created_at", "id"],
  "user.fields": ["username", "name"],
  expansions: ["author_id"],
});
```

and it's definitely returning truncated text. Am I doing something wrong?

For [this tweet](https://twitter.com/dogemperor/status/1604137303940640768) 

```
for (const tweet of search) {
  console.log("tweet.text: ", tweet.text);
}
```

it logs 

```
tweet.text:  RT @SayethSimon: There’s a lot of chatter about 80 FBI agents looking at “twitter posts”

Social listening and social monitoring is an esse…
```
