### ISSUE TITLE
Uploading attachments via DM raises an error

### ISSUE THREAD

**Issue by Rodolfo-Bevione** [PLhery/node-twitter-api-v2#282]
If I understood correctly, the flow to upload an attachment to some private conversation is as follows

1) Retrieve the contact ID of the user you're trying to message
2) Call `twitterClient.v1.uploadMedia(someBuffer, {type: png})`; this should return a media id
3) call `twitterClient.v1.sendDm({recipient: userId, text: "", attachment: mediaId})`

However, step 3 in the given list is failing with the following message

`Request failed with code 400 - event.message_create.message_data.attachment: Cannot deserialize value of type 'com.twitter.api.dm.client.public.request.json.AttachmentJsonRequest' from String value (token 'JsonToken.VALUE_STRING') (Twitter code 214)`

Is this the correct place to report such a behavior?

Kind regards

**Comment by alkihis** [comment]
Hi :)
A GitHub discussion seems to be more appropriate for those kind of questions.

In your first call, you may have forgot to use `target: 'dm'`. ([see doc](https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/v1.md#upload-a-picturevideosubtitle-to-twitter))
```ts
const mediaId = await twitterClient.v1.uploadMedia(someBuffer, { type: 'png', target: 'dm' })
```

**Comment by Rodolfo-Bevione** [comment]
I'm afraid doing so raises the same error. Is it possible that it's a problem with Twitter?

**Comment by alkihis** [comment]
You're using `attachment` property incorrectly.
I recommand you to use a code editor that supports TypeScript definitions, even if you use JavaScript, as those kind of errors can be detected statically :D 

```ts
twitterClient.v1.sendDm({ recipient: userId, text: '', attachment: { type: 'media', media: { id: mediaId } } })
```
