### ISSUE TITLE
v2: Add reverse_chronological endpoint

### ISSUE THREAD

**Issue by tonka3000** [PLhery/node-twitter-api-v2#288]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add support for https://api.twitter.com/2/users/:id/timelines/reverse_chronological

**Describe alternatives you've considered**
There are no alternatives when you wanna use OAuth2 which only works in v2.

**Additional context**
Twitter announced today the reverse_chronological endpoint, which is the same as the home_timeline feature from v1, where somebody see the timeline of the authenticated user + followers.
 https://api.twitter.com/2/users/:id/timelines/reverse_chronological

**Comment by alkihis** [comment]
Thank you for creating the issue.
I will add this to the lib this week-end.

**Comment by tonka3000** [comment]
Thank you for providing this awesome library

**Comment by alkihis** [comment]
Available on 1.12.2 :)
