### ISSUE TITLE
How to upload a base64 file

### ISSUE THREAD

**Issue by iota-unum** [PLhery/node-twitter-api-v2#290]
How can i upload a base64 file?

I have a DataUrl string of an image
I tried with:
const mediaId = await client.v1.uploadMedia(Buffer.from([DataUrl]), { mimeType: EUploadMimeType.Png });
as per documentation

I tried with:
await client.v1.uploadMedia(Buffer.from(DataUrl, 'base64'), { mimeType: 'image/png' }

Twitter-api sends me a 400 error 'media type unrecognized.'

It works fine with the standard wrapper 
const res = await client.v1.post( 
       'media/upload.json',
      { media_data: DataUrl },
      { prefix: 'https://upload.twitter.com/1.1/' }
    );

But I need the "chunked upload" for larger image sizes.

Thanks

**Comment by alkihis** [comment]
This isn't an issue, your base64 encoding is most likely to be invalid.
See this discussion. https://github.com/PLhery/node-twitter-api-v2/discussions/264
