### ISSUE TITLE
Missing favorites/list in v1

### ISSUE THREAD

**Issue by AuroraDysis** [PLhery/node-twitter-api-v2#296]
**Is your feature request related to a problem? Please describe.**

I can't find favorites/list endpoint in v1 client
https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/get-favorites-list

**Describe the solution you'd like**

add favorites related endpoint

**Comment by alkihis** [comment]
Hi,
Right now this lib focuses first on implementing endpoints available on v2 API (and likes are: https://developer.twitter.com/en/docs/twitter-api/tweets/likes/api-reference/get-tweets-id-liking_users).
v1 endpoints were implemented if they haven't a v2 counterpart.

You can still use `.v1.get('favorites/list.json')`.
I'll be happy to review a possible pull request of you to add an endpoint wrapper to the lib!

**Comment by AuroraDysis** [comment]
> Right now this lib focuses first on implementing endpoints available on v2 API (and likes are: https://developer.twitter.com/en/docs/twitter-api/tweets/likes/api-reference/get-tweets-id-liking_users).
v1 endpoints were implemented if they haven't a v2 counterpart.

Thanks, but one thing I would like to point out is that the Twitter API v2 has a very low month cap.
https://twittercommunity.com/t/tweet-monthly-cap-on-v2-is-so-low/162168
So in many cases, people have to use Twitter API v1.

> I'll be happy to review a possible pull request of you to add an endpoint wrapper to the lib!

Ok, then I will open a pull request soon.
