### ISSUE TITLE
Only getting partial information from tweet and user retrieval

### ISSUE THREAD

**Issue by arthurb123** [PLhery/node-twitter-api-v2#30]
Hello, I have been messing around with this library for a while now but despite whichever authentication method I use (bearer token, or app/access credential object), I am unable to get the full information from tweet and user retrieval.
For instance, for tweets I am only able to get { id, text } while I want to be able to get { created_at?, attachments?, etc. } - this also applies to retrieving the user data for a user, I always am only able to get partial information.
I am unable to find any hint or clue in the available documents, am I doing something wrong with authentication or am I missing something else?
Thanks in advance, great library nevertheless!

**Comment by arthurb123** [comment]
Oh wow, I switched to the v1 API instead of using the v2 API and it all works fine now.
My bad, closing the issue.

**Comment by PLhery** [comment]
Hello Arthur,

Indeed, currently to use the API v2 endpoints you need to add the app to a project https://developer.twitter.com/en/portal/projects-and-apps
