### ISSUE TITLE
[bug] tweetLikedBy total returned doesn't match twitter likes count

### ISSUE THREAD

**Issue by HRK44** [PLhery/node-twitter-api-v2#300]
**Describe the bug**
I'm calling tweetLikedBy on some tweets and the total shown on twitter is different from the count I get (686 vs 610 for example).
Any reason why?

**To Reproduce**
```
        const usersPaginated = await roClient.v2.tweetLikedBy('1534363946773250051', { asPaginator: true  });

        let i = 0;
        for await (const user of usersPaginated) {
            console.log(user.id);
            i++;
        }
        console.log(i);
```

**Expected behavior**
Count of likes on twitter matches the count returned in the results

**Comment by alkihis** [comment]
Hi,
This isn't a bug, this is how Twitter API behaves.
If likers of a tweet are suspended or private accounts, they won't appear in result.
So you must except a different count between like count and fetched likers IDs.
