### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by NeonWizard** [PLhery/node-twitter-api-v2#308]
**Describe the bug**
Unable to upload media. Receiving the error "Segments do not add up to provided total file size." I'm trying to post a GIF that's 9.9MB in size. The code fails on upload media.

**To Reproduce**
```js
async function postTweet() {
  const client = new TwitterApi({
    appKey: process.env.API_KEY,
    appSecret: process.env.API_SECRET_KEY,
    accessToken: process.env.ACCESS_TOKEN,
    accessSecret: process.env.ACCESS_TOKEN_SECRET
  })

  const mediaId = await client.v1.uploadMedia('mygif.gif')

  const { data: createdTweet } = await client.v2.tweet('Another day in paradise!', { media: {media_ids: [mediaId]}})
}
```

**Version**
 - Node.js version
   - v16.13.2
 - Lib version
   - 1.12.2 
 - OS (especially if you use Windows)
   - Ubuntu

**Comment by alkihis** [comment]
Can you upload somewhere the Gif file you're using to test it on my side?

**Comment by NeonWizard** [comment]
I found the issue - for some reason, the GIF wasn't complete on the filesystem yet, although the package I was using to generate it was emitting the file descriptor being closed. Waiting 3 seconds made this issue disappear 🤷🏻 .
