### ISSUE TITLE
Minimal working example -- await is only valid in async function

### ISSUE THREAD

**Issue by danielnjoo** [PLhery/node-twitter-api-v2#31]
Hi, I'm only lightly familiar with Promises and always get confused by them. Realize that as noted in the docs all return types are wrapped inside Promises. However, when I try to run any of the short examples (verbatim) I get hit with the `await is only valid in async function error`. 

Was wondering if you had any minimal example that would work or resolve the Promise? I tried a few paradigms (from Google) but none seemed to work. Thanks.

**Comment by franciscohanna92** [comment]
@danielnjoo Maybe you can supply a code snippet of how you are using the package. That way it will be easier to help you.

**Comment by franciscohanna92** [comment]
@danielnjoo An alternative to `async / await` is to use `then`:

```javascript
twitterClient.v1.tweet('Hello, this is a test.')
    .then(response => console.log(response)) // Here you handle the response from the Twitter API
    .catch(error => console.error(error)); // Here you handle any errors
```

If you want to use `async / await` you have to wrap the call in an async function:

```javascript
async function postTweet() {
   try {
       const response = await twitterClient.v1.tweet('Hello, this is a test.');
       console.log(response);
   } catch(error) {
       console.error(error)
   }
}
```

**Comment by PLhery** [comment]
Thanks a lot @franciscohanna92 :)

We should indeed clarify this in the readme snippet, thanks for the report @danielnjoo

**Comment by doup** [comment]
As mentioned by @franciscohanna92 `async/await` is sugar on top of JS Promises. Alternatively, if you're in Node, and you want to make your code `async/await` on your entry script, use this pattern:

```
(async () => {
    // Your await code goes here
})();
```

Or if you prefer named functions:

```
async function main() {
    // Your await code goes here
}

main();
```

**Comment by alkihis** [comment]
All the above examples applies in the CommonJS mode of Node.js, that does not (and will never) allow top-level `await` as specified in ECMAScript.

Indeed, none of the README examples (for sake of simplicity) are presented with an underlying async wrapper.
When I wrote it, I've supposed reader knows about `async`/`await` pattern in JavaScript. 

To summarize all messages above, here's a quick start for this package:
- If you're in CommonJS mode (the Node default):
**In TypeScript**:
```ts
import TwitterApi from 'twitter-api-v2'

(async () => {
  // Starts all your script logic here.
  const client = new TwitterApi({ ... })
  const followers = await client.v2.followers('12')
})().catch(console.error)
```
**In regular JS**:
```ts
const { TwitterApi } = require('twitter-api-v2')

(async () => {
  // Starts all your script logic here.
})().catch(console.error)
```

- If you're in ECMA modules mode (`"type": "module"` in package.json or your script ends with `.mjs` extension):
```js
// please do not use default import, it will not work!
import { TwitterApi } from 'twitter-api-v2' 

const client = new TwitterApi({ ... })

// Starts your script logic at top level, its okay :)
const followers = await client.v2.followers('12')
```
