### ISSUE TITLE
Cannot authenticate on aws lambda - ApiResponseError: Request failed with code 400 

### ISSUE THREAD

**Issue by ng-saas** [PLhery/node-twitter-api-v2#313]
Hello, first of all thank you for creating this library.

I have already used it in another project.
Now I wanted to use it again.
For hosting front-end and back-end I decided to use aws (lambda and amplify).
But now I am not able to authenticate a user.
I use the 3-legged authentication process and when I do it locally with an express server it works.
But when I do the same on aws lambda, I get the following error when I try to generate the auth link.

`ApiResponseError: Request failed with code 400 - Bad Authentication data. (Twitter code 215)`

Here is how I use it:

`
const client = new TwitterApi({  
      appKey: APP_CONSUMER_KEY,  
      appSecret: APP_CONSUMER_SECRET  
  });
 `
 `const link = await client.generateAuthLink(callback_url);  
 `
 
 I also implemented the oauth generate auth link on my own using oauth1.0a.
 This way I was able to generate the auth link and use it.

Does anyone have any ideas?

**Comment by alkihis** [comment]
Hello,

Your environement variables are most likely to be `undefined`. Check your configuration.

**Comment by ng-saas** [comment]
Thanks for your reply.
Unfortunately that is not the issue, I checked the variables and even hard coded them for testing.

**Comment by ng-saas** [comment]
I think I fixed the issue.


Before I was importing and calling TwitterAPI like this:
`
import TwitterApi from "twitter-api-v2";
const twitter_client = new TwitterApi(tokens);
`
Now I do it this way:
`
import twitter_api_v2_1 from "twitter-api-v2";
const twitter_client = new twitter_api_v2_1.TwitterApi(tokens);
`

So I think, I have more of an JS setup issue rather than a bug in your packages.

Do you know why this happens?
I use `"type": "module"`  in my package.json to be able to use the import statements rather than require.

Maybe I have to switch back to require, so that it works

**Comment by alkihis** [comment]
Some way or another your import is not made properly by the node engine :/
You can also use `require` (as this package is a CommonJS one)
```ts
const { TwitterApi } = require('twitter-api-v2') 
```
