### ISSUE TITLE
Stream is triggered again when I reply to the original tweet I received on stream

### ISSUE THREAD

**Issue by Nithur-M** [PLhery/node-twitter-api-v2#318]
Hi, I am using stream to receive tweets that mention my account and reply to those tweets. But the reply function is triggering the stream function twice.
here is my code:
```
stream.on(
  // Emitted when a Twitter payload (a tweet or not, given the endpoint).
  ETwitterStreamEvent.Data,
  eventData => {
   client.v2.reply(
    'Thank you',
    eventData.data.id,
    )
  }
);
```
What is the issue here? or am I doing anything wrong?
Thank you.

**Comment by alkihis** [comment]
This isn't an issue, this is directly caused by Twitter.
When you listen tweet with an "@" rule, you receive tweets mentioning the account AND tweets of the account itself.

**Comment by Nithur-M** [comment]
But I am using rules with AND logic to check for tweets. 

What is the workaround for this?

**Comment by alkihis** [comment]
You can ignore tweets that comes from your account. It is a common pattern in tweet stream handling.

```ts
const me = await client.v2.me()

stream.on(
  // Emitted when a Twitter payload (a tweet or not, given the endpoint).
  ETwitterStreamEvent.Data,
  eventData => {
    // be sure to add "tweet.fields: ['author_id']" in your stream request, otherwise 'author_id' property will not exists.
    if (event.data.author_id === me.data.id)  // ignore tweets coming from me
      return;

    client.v2.reply(
      'Thank you',
      eventData.data.id,
    )
  }
);
```

**Comment by khanakhun** [comment]
@Nithur-M  Hi, I have the same requirement as you mentioned, I'm creating a bot that gets tweets with specific mentions and replies to them, the problem I'm facing is with authentication.
1: if I use the Bearer token then i can get incoming tweet streams but i can't reply using this auth.
2: If I use apiKey, apiSecret, access_token,access_token_sercret, then i can reply to tweet but getting auth error while using filter API to get tweet stream
