### ISSUE TITLE
[bug] I can't refresh tokens.

### ISSUE THREAD

**Issue by wholelott4** [PLhery/node-twitter-api-v2#319]
"twitter-api-v2": "^1.12.0",
node: v16.14.2

`
const twitterAPI = new twitter.TwitterApi({clientId: 'ABC', clientSecret: 'DEF'})
const { twitterAPI: refreshedClient, accessToken, refreshToken: newRefreshToken } = await twitterAPI.refreshOAuth2Token(user.twitter.refreshToken);
`

I am receiving an 401 Unauthorized error, with the message: " Missing valid authorization header ".

the {user.twitter.refreshToken} is giving me the correct refresh token, already debugged that.

To obtain the refresh token, I am using the method `loginWithOAuth2` and I get all the information correctly.

**Comment by alkihis** [comment]
Hi,

Tested your code like this:
```ts
const credentials = {
    clientId: process.env.OAUTH2_CLIENT_ID!,
    clientSecret: process.env.OAUTH2_CLIENT_SECRET,
  }

  const tokenStore = {
    refreshToken: '---redacted--'
  }

  const twitterAPI = new TwitterApi(credentials);
  const { client: refreshedClient, accessToken, refreshToken: newRefreshToken } = await twitterAPI.refreshOAuth2Token(tokenStore.refreshToken);

  console.log(accessToken, newRefreshToken) // Everything is ok.
```
and got all my tokens refreshed correctly, no Authorization issue.

Check if your client ID and client secret are correctly defined.

If the problem continues, please enable [request debugging](https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/errors.md#advanced-debug-all-made-requests) and paste request/response content here.

**Comment by npomfret** [comment]
@wholelott4 did you figure this out?  I have exactly the same issue
