### ISSUE TITLE
Explain rate limiting

### ISSUE THREAD

**Issue by doup** [PLhery/node-twitter-api-v2#32]
From the documentation is not clear how this library handles rate-limiting.

What happens if I try to fetch too much data, too fast. Will it internally pause until it's safe to continue? So, for me -as a library user- will be transparent and I'll get my data eventually?

Thanks!

**Comment by alkihis** [comment]
Since https://github.com/PLhery/node-twitter-api-v2/pull/47 is merged, you now have some explaination of rate limit handling inside this lib :)
