### ISSUE TITLE
Query about fetching tweet replies/comments.

### ISSUE THREAD

**Issue by muhitrhn** [PLhery/node-twitter-api-v2#327]
### Discussed in https://github.com/PLhery/node-twitter-api-v2/discussions/324

<div type='discussions-op-text'>

<sup>Originally posted by **muhitrhn** July  8, 2022</sup>
Is it possible to fetch replies/comments of a specified tweet.</div>

**Comment by alkihis** [comment]
This isn't a place for asking for advice about Twitter API. Please stick to discussions, or use https://twittercommunity.com/.

**Comment by muhitrhn** [comment]
@alkihis And of course, if I posted here, that means I want to know if it’s possible by this Package.
