### ISSUE TITLE
ETwitterStreamEvent.DataKeepAlive not emitted

### ISSUE THREAD

**Issue by noname202** [PLhery/node-twitter-api-v2#33]
`When using the Streaming API I ran into an issue with the ETwitterStreamEvent.DataKeepAlive never being fired. From looking at the source of TweetStream.ts I found out that this is caused by the use of strict string comparison (not allowing for type conversion) in the corresponding code.  Changing "===" to "==" fixed the issue for me. However I didn't check if allowing for type conversion has any other implications.

```
this.res.on('data', chunk => {
      if (chunk === '\r\n') {
        return this.emit(ETwitterStreamEvent.DataKeepAlive);
      }

      this.parser.push(chunk);
    });
  }
```

**Comment by PLhery** [comment]
Fixed in 1.1.1
