### ISSUE TITLE
some docs correction

### ISSUE THREAD

**Issue by rayeaster** [PLhery/node-twitter-api-v2#339]
https://github.com/PLhery/node-twitter-api-v2/blob/36821932dbde93129168e8b47af4e1e377552bde/doc/basics.md#make-requests-behind-a-proxy

- should be `new TwitterApi(bearToken, {'httpAgent': proxyAgent})` instead of `new TwitterApi(bearToken, {proxyAgent})` according to https://github.com/PLhery/node-twitter-api-v2/blob/6cd5558d82d036371e30e73a085e1b3a4517447e/src/types/client.types.ts#L70

**Comment by ann-sketch** [comment]
I think this issue has been fixed already, why is it not closed....
