### ISSUE TITLE
Unsupported Authentication

### ISSUE THREAD

**Issue by miduh** [PLhery/node-twitter-api-v2#340]

**Comment by narhzih** [comment]
The .listDmEvents() doesn't exist on client.v2. However, when I tried to use it on v1 ( client.v1.listDmEvents() ), I get the following errors:

`ApiResponseError: Request failed with code 403
    at RequestHandlerHelper.createResponseError 
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  error: true,
  type: 'response',
  code: 403,
  headers: {
    perf: '7626143928',
    'content-type': 'application/problem+json',
    'cache-control': 'no-cache, no-store, max-age=0',
    'content-length': '292',
    'x-transaction-id': '...',
    'x-response-time': '2',
    'x-connection-hash': '...',
    date: 'Sun, 05 Mar 2023 07:02:31 GMT',
    server: 'tsa_b',
    connection: 'close'
  },
  rateLimit: undefined,
  data: {
    title: 'Unsupported Authentication',
    detail: 'Authenticating with OAuth 1.0a User Context is forbidden for this endpoint.  Supported authentication types are [OAuth 2.0 Application-Only].',
    type: 'https://api.twitter.com/2/problems/unsupported-authentication',
    status: 403
  }
}`

**Comment by narhzih** [comment]
> The .listDmEvents() doesn't exist on client.v2. However, when I tried to use it on v1 ( client.v1.listDmEvents() ), I get the following errors:
> 
> `ApiResponseError: Request failed with code 403 at RequestHandlerHelper.createResponseError at IncomingMessage.emit (node:events:525:35) at IncomingMessage.emit (node:domain:489:12) at endReadableNT (node:internal/streams/readable:1359:12) at processTicksAndRejections (node:internal/process/task_queues:82:21) { error: true, type: 'response', code: 403, headers: { perf: '7626143928', 'content-type': 'application/problem+json', 'cache-control': 'no-cache, no-store, max-age=0', 'content-length': '292', 'x-transaction-id': '...', 'x-response-time': '2', 'x-connection-hash': '...', date: 'Sun, 05 Mar 2023 07:02:31 GMT', server: 'tsa_b', connection: 'close' }, rateLimit: undefined, data: { title: 'Unsupported Authentication', detail: 'Authenticating with OAuth 1.0a User Context is forbidden for this endpoint. Supported authentication types are [OAuth 2.0 Application-Only].', type: 'https://api.twitter.com/2/problems/unsupported-authentication', status: 403 } }`
