### ISSUE TITLE
autoReconnect not catching ECONNRESET

### ISSUE THREAD

**Issue by micodeyt** [PLhery/node-twitter-api-v2#36]
Hello,

I can't make autoReconnect feature work, I'm getting a ECONNRESET error that does not trigger the reconnection logic.
```
{
  "type": "connection error",
  "error": {
    "code": "ECONNRESET"
  }
}
```

My code :
```
this.tweetsStream = await this.twitterClient.v2.searchStream({
  ...
})
this.tweetsStream.autoReconnect = true
```

**Comment by PLhery** [comment]
Hello Micode, thanks for the report

I guess it's related to this issue https://github.com/PLhery/node-twitter-api-v2/issues/33 which will be fixed by this PR https://github.com/PLhery/node-twitter-api-v2/pull/34
