### ISSUE TITLE
How to use proxy v1.1

### ISSUE THREAD

**Issue by canyesilyurt** [PLhery/node-twitter-api-v2#361]
Hello, i am using v1.1 api. My connect method 
![image](https://user-images.githubusercontent.com/36952967/189629870-10ec64eb-e7ce-4550-bdba-b242b1176782.png)

const client = new TwitterApi({
appKey: 'CjulERsDeqhhjSme66ECg',
appSecret: 'IQWdVyqFxghAtURHGeGiWAsmCAGmdW3WmbEx6Hck',
accessToken: 'accestoken',
accessSecret: 'secret',       
});

How can use all request w/ proxy

*Note: For questions about how to use an endpoint, or problems related to Twitter API than the lib itself, please use the GitHub Discussions instead of opening a new issue*.

**Comment by canyesilyurt** [comment]
Closed? Why?

**Comment by alkihis** [comment]
As explicitly described in issue template, issues are not a place to ask questions on this repository, but for reporting bugs. Discussions are meant to seek help.

Furthermore, documentation about proxies is available on the first page of docs: https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/basics.md#make-requests-behind-a-proxy

And related issue + pull can be found in a 5 secs search on GitHub: #157 + #149.
