### ISSUE TITLE
Cannot read property 'v1' of undefined

### ISSUE THREAD

**Issue by ShireDev** [PLhery/node-twitter-api-v2#37]
I want to use the read only client but when i use it it say: Cannot read property 'v1' of undefined
Someone can help me?
![image](https://user-images.githubusercontent.com/70603474/124397222-013db000-dd0f-11eb-9492-a7bd51272652.png)

**Comment by alkihis** [comment]
Hello :) 
You seems to read from the wrong property!
To use your Twitter client, you must use `readOnly` property from client: `const roClient = TwitterClient.readOnly`.
