### ISSUE TITLE
ApiResponseError: Request failed with code 403

### ISSUE THREAD

**Issue by gbytes-me** [PLhery/node-twitter-api-v2#371]
**Describe the issue**
When I try to upload media using **v1.uploadMedia**, get the following set of errors

**code**
   refreshedClient = await getRefreshedToken(userName);
    const mediaId = await refreshedClient.v1.uploadMedia('001.png');
    await refreshedClient.v2.tweet({text:"Tweet with an image!", media:{media_ids: [mediaId]}})

**features used**
OAuth2
await client.v1.uploadMedia

**Version**
Node v18.9.0
API 1.12.7
Mac OSX
Elevated access to v1 and v2 api

**Error Output**

> /node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:103
>         return new types_1.ApiResponseError(errorString, {
>                ^
> 
> ApiResponseError: Request failed with code 403
>     at RequestHandlerHelper.createResponseError (/Users/<user>/projects/<projectname>/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:103:16)
>     at RequestHandlerHelper.onResponseEndHandler (/Users/<user>/projects/<projectname>/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:252:25)
>     at IncomingMessage.emit (node:events:525:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   error: true,
>   type: 'response',
>   code: 403,
>   headers: {
>     perf: '.......',
>     'cache-control': 'no-cache, no-store, max-age=0',
>     'content-length': '0',
>     'x-transaction-id': '.....',
>     'x-response-time': '161',
>     'x-connection-hash': '........',
>     date: 'Mon, 19 Sep 2022 21:40:16 GMT',
>     server: 'tsa_k',
>     connection: 'close'
>   },
>   rateLimit: undefined,
>   data: ''
> }
> 
>

**Comment by AyoubKasmi** [comment]
same issue

**Comment by alkihis** [comment]
You can't upload a media with an OAuth2 token.

**Comment by mopscr** [comment]
what do I need then to upload media can't figure out
this is my code
```
import { TwitterApi } from "twitter-api-v2";
import dotenv from "dotenv";
import { logger } from "../logger";

dotenv.config({ path: <PATH_TO_ENV> });

const twitterClient = new TwitterApi({
  appKey: process.env.api_key!,
  appSecret: process.env.api_secret!,
  accessToken: process.env.api_access!,
  accessSecret: process.env.api_tokenSecret!,
});

export const rwClient = twitterClient.readWrite;

export async function sendTweet(post_title: string, media_file: string) {
  const media_id = await twitterClient.v1.uploadMedia(
    "./cat.jpg"
  );
  const tweet = await rwClient.v2.tweet(post_title, {
    media: { media_ids: [media_id] },
  });
  logger.log("info", tweet);
}

sendTweet("test", "cat");
```

im using the last line only for testing and environment variables are all correct i just changed it to show code

**Comment by alkihis** [comment]
@arunlz i've already replied to this. It's simple: you **can't** use OAuth2 to upload a media.
