### ISSUE TITLE
Track my mentions on v2 with stream

### ISSUE THREAD

**Issue by Valentine-Mario** [PLhery/node-twitter-api-v2#387]
With the v1 api, I could easily track my mentions as this 
```js
client.stream('statuses/filter', { track: ['@myTwitterHandle']
```
But the tracking feature seems to be missing in the v2 instance which would lead me to track my mentions as this 

```js
stream.on(ETwitterStreamEvent.Data, async tweet=>{
  if(tweet.data.text.includes("@myTwitterHandle")){
    console.log(tweet.data.text, "/n/n")
  }
});
```

This seems relatively slow and inefficient. Is there a more optimized way of tracking all my mentions via stream on the v2 instance

**Comment by fabioselau077** [comment]
resolved?

**Comment by bayramn** [comment]
> completed

How?
