### ISSUE TITLE
ApiResponseError: Request failed with code 401 - Request token missing

### ISSUE THREAD

**Issue by dd-pardal** [PLhery/node-twitter-api-v2#39]
This is the code I tried (the right tokens and secrets are there):

```js
import { TwitterApi } from "twitter-api-v2";

const consumerClient = new TwitterApi({
    appKey: "APP KEY",
    appSecret: "APP SECRET",
    accessToken: "ACCESS TOKEN",
    accessSecret: "ACCESS TOKEN SECRET"
}).readWrite;
const client = await consumerClient.login();
```

This throws an `ApiResponseError: Request failed with code 401` error. I tried the `twit` package and it worked just fine, so I think this is an issue specific to this library. The error's `data` property is `{ 'Request token missing': '' }`.

**Comment by alkihis** [comment]
Hello! Thanks for your submission.

The `.login` method takes a `oauthVerifier` as first param. It should be used to authentificate a user in a 3-legged auth flow.

A small example is [available here](https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/auth.md#case-1-user-has-been-redirected-to-your-callback-url).
If it doesnt resolve your problem, drop an update.

If you're juste trying to use your client with **already known and valid** accessTokens, you **don't need to use the `.login` method**! You can use the `consumerClient` directly.

**Comment by dd-pardal** [comment]
Thanks, @alkihis! I've tried several combinations with `.appLogin()` and `.login()`, but indeed the right thing to do was to use the `consumerClient` directly.
