### ISSUE TITLE
[bug] Option "tweet.fields":" public_metrics" only returns retweet_count, the rest are always 0

### ISSUE THREAD

**Issue by alejandromc23** [PLhery/node-twitter-api-v2#390]
**Describe the bug**
Option `"tweet.fields":" public_metrics"` only returns `retweet_count`, others values like `like_count` are always 0

**To Reproduce**
Endpoint `tweets/search/recent` combined with options argument: 
` options: { 'tweet.fields': ['public_metrics']}
 `

**Expected behavior**
Return real `public_metrics`

**Comment by alkihis** [comment]
How is this the fault of the library?! 😭

**Comment by alejandromc23** [comment]
tryed with this and it worked: `https://api.twitter.com/2/tweets/search/recent?query=from:amascort17&tweet.fields=public_metrics`
And trying with lib it did not, so I supposed it was libs logic... :face_exhaling:
