### ISSUE TITLE
Use a previously available next_token

### ISSUE THREAD

**Issue by israelidanny** [PLhery/node-twitter-api-v2#393]
**Is your feature request related to a problem? Please describe.**
I am trying to asynchronously load some data with pagination, and to better control rate limiting it would be very useful for me instead of paginating everything in one lambda function I could make a request with a previously available next_token to me.

**Describe the solution you'd like**
It would be ideal if I could make a non paginated request supplying next_token.

**Comment by alkihis** [comment]
You can still give a `next_token` parameter to a function returning a paginator.

```ts
const timeline = await client.v2.userTimeline('12', { next_token: '_your_token_' });

// Get the received data
const tweets = timeline.tweets;
    
// Get next token received
const nextToken = timeline.data.meta.next_token;
```
