### ISSUE TITLE
DM Events?

### ISSUE THREAD

**Issue by jamdav16** [PLhery/node-twitter-api-v2#395]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, but Twitter announced the v2 endpoint for DM's: https://developer.twitter.com/en/docs/twitter-api/direct-messages/lookup/api-reference/get-dm_events

**Describe the solution you'd like**
For this API client to support the new v2 endpoint for DM's, any timeline for this happening?

**Comment by alkihis** [comment]
Available in 1.13.0 :)
