### ISSUE TITLE
Plugin rate-limit issue

### ISSUE THREAD

**Issue by camiaei** [PLhery/node-twitter-api-v2#412]
I'm having a weird issue regarding the rate-limit plugin:

I'm hitting the same endpoint from two different places (my local machine/my production environment) and I'm getting two different .remaining and .reset values.

In both places I am using the same API keys.

Does it make any sense? On both sides you should get the same values, right? 🤔

**Comment by PLhery** [comment]
I think both side are supposed to be the same value indeed ;
I don't think it comes from the library though.

**Comment by alkihis** [comment]
Hi,
Different values can mean:
- The reset timer has been hit, therefore remaining count is reset
- Different account 
- Different auth methods
- Twitter can also "forget" some requests and led to different rate limiting values sometimes...
- Sometimes, your client can bypass rate limiting if Twitter allows you to do so, then incoherent rate limit results can occur
