### ISSUE TITLE
Unable to upload media using  with OAuth2 authentication 

### ISSUE THREAD

**Issue by dev-bre** [PLhery/node-twitter-api-v2#417]
I am using OAuth2 authentication, and even though I see that the uploadMedia function is only available for V1, it should still be possible to use it.

Unfortunately I keep getting 403 Forbidden error when I call it.

any idea why?

Please don't tell me it is only available with OAuth1.1 auth... please!

**Comment by Arikatsu** [comment]
sorry but yes
> - OAuth 2.0 Authorization Code with PKCE (fine-grained scopes, API v2 only)

**Comment by Intevel** [comment]
@dev-bre Do you found an way to upload media with Oauth?
