### ISSUE TITLE
Using "next_page_token" on "tweetLikedBy"

### ISSUE THREAD

**Issue by Ketcap** [PLhery/node-twitter-api-v2#439]
**Is your feature request related to a problem? Please describe.**
When I'm using "v2.tweetLikedBy" I need to pass argument `asPaginator:true` and I cannot pass "next_page_token". typescript yells and does not work.

**Describe the solution you'd like**
I would like to have the "next_page_token" param available to user.

**Describe alternatives you've considered**
I don't think there's an alternative on here, I might have missed tho.
I've check this issue but not applicable for "v2.tweetLikedBy" https://github.com/PLhery/node-twitter-api-v2/issues/393

**Additional context**
When I get likes of the tweet after getting "429" I'd like to continue where I've left off.

**Comment by alkihis** [comment]
Hi,
How about `pagination_token`?
No parameter is named `next_page_token` for this endpoint (please see documentation https://developer.twitter.com/en/docs/twitter-api/tweets/likes/api-reference/get-tweets-id-liking_users).

**Comment by delivey** [comment]
Running into the same issue.
