### ISSUE TITLE
API V2 Stream TooManyConnections

### ISSUE THREAD

**Issue by quarkhadron** [PLhery/node-twitter-api-v2#440]
Been getting TooManyConnections for the past few days. Everytime I try to run the app, it keeps crashing because too many connection. However, I tried to stop the app, stream.close() a few times and still haven't solved the issue.

Here is the code 
```
const stream = await Twitter.v2.searchStream({ autoConnect: false });

await stream.connect({ autoReconnect: true, autoReconnectRetries: Infinity }).then(console.log('Connecting to Twitter...'));

 //await stream.close();
```

Here is part of the error response rateLimit: { limit: 40000, remaining: 39995, reset: 1673846259 }. It has not reached the limit yet, however, the app just won't reconnect to the stream. 

How to solve this problem?

**Comment by zidane-sc** [comment]
@quarkhadron have you found the solution bro?

**Comment by npomfret** [comment]
Are you using the Pro version of the api?
