### ISSUE TITLE
`x-app-limit-24hour-x` header properties

### ISSUE THREAD

**Issue by hkong-mitre** [PLhery/node-twitter-api-v2#495]
How do I use this library to get the `x-app-limit-24hour-reset`, `x-app-limit-24hour-limit`, and `x-app-limit-24hour-remaining` header properties?  

I tried using the `@twitter-api-v2/plugin-rate-limit` plugin, using [this code in the examples](https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/rate-limiting.md#extract-rate-limit-information-with-plugins), but it returns the `rateLimit` property, whereas I need the `x-app-limit-24hour-x` header properties, which are different and (for my application at least, more useful).

Thank you in advance,

**Comment by alkihis** [comment]
Hello,

As [1.15.2](https://github.com/PLhery/node-twitter-api-v2/releases/tag/1.15.2) it is now available in `rateLimit.day` property.

A `rateLimit` object is a `TwitterRateLimit`

```ts 
interface SingleTwitterRateLimit {
  limit: number;
  reset: number;
  remaining: number;
}

interface TwitterRateLimit extends SingleTwitterRateLimit {
  day?: SingleTwitterRateLimit;
}
```
