### ISSUE TITLE
Module 'fs' has no default export

### ISSUE THREAD

**Issue by filippkowalski** [PLhery/node-twitter-api-v2#56]
I'm receiving `Module '"fs"' has no default export.` error when trying to compile and deploy script containing `twitter-api-v2` package, is there any specific requirement so this error won't appear?
![image](https://user-images.githubusercontent.com/10477861/130261656-fadbcb1b-d348-4655-ab54-3249f82e7271.png)

**Comment by filippkowalski** [comment]
Adding `--allowSyntheticDefaultImports` to the command solved it for me
![image](https://user-images.githubusercontent.com/10477861/130264380-7457516a-8292-416a-840c-5cfd035bcc04.png)

**Comment by PLhery** [comment]
Hello,

allowSyntheticDefaultImports is supposed to be true by default, maybe it's manually set to false in you tsconfig.json file?

Indeed we could set it to false ourselves to maximize compatibility :)

**Comment by alkihis** [comment]
Now merged and available in 1.4.0 :)
