### ISSUE TITLE
[Feature Request] Add option to disable all console.log

### ISSUE THREAD

**Issue by HapLifeMan** [PLhery/node-twitter-api-v2#66]
Hello,

Could you add an option to disable everything printing in the console?
I saw a `debug` property set to `false` by default in the settings and a condition using it but it's still printing in the console.

Is it a bug or a feature not fully implemented yet?

Thanks!

**Comment by alkihis** [comment]
Hi, sorry for that!
It's not intended that the lib print something in the console.

What's printed in your console? Do you know which method produce that result?

**Comment by HapLifeMan** [comment]
Sorry, the error was automatically handled and printed by the framework I use... 😅
