### ISSUE TITLE
Media type is not detected correctly when file is temporary

### ISSUE THREAD

**Issue by HapLifeMan** [PLhery/node-twitter-api-v2#68]
Hello,

I'm using the `uploadMedia()` helper to upload a file to Twitter from a user input (through HTML form).
The file is automatically uploaded to my server in the `/tmp` folder and I'm trying to upload this file to Twitter which has a `.tmp` extension, so the detection is not correct because of that:
https://github.com/PLhery/node-twitter-api-v2/blob/ff4c0f5335a360163e57a5761ee3f2eec8180c37/src/v1/media-helpers.v1.ts#L71-L80

I know I can provide the type in the options (and it's working fine), but if that's possible to detect the mime type from the `.tmp` file, that would be awesome! 😊

**Comment by PLhery** [comment]
Thanks for the suggestion, I feel that it's not trivial to detect it from the content of the file, and this would make the library less light. I don't know if you have any opinion on this @alkihis?

Though i guess you could easily use https://github.com/sindresorhus/file-type/ yourself :)

**Comment by PLhery** [comment]
(maybe we can also add an example on how to use it with file-type to the doc)

**Comment by alkihis** [comment]
Hello, and thanks for the suggestion too :)
Yet a file-by-content detection is not implemented, and it seems not to be an easy task to do this.
We don't want to include a 3rd-party lib into this project, so we don't except to support this kind of detection (at least for now).

Of course, we can include an example with file-type [here](https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/v1.md#upload-a-picturevideosubtitle-to-twitter) if needed :)
It's not explicitly specified in the doc (and it should be), but you can give a raw MIME type to the `type` argument of `.uploadMedia`.

**Comment by alkihis** [comment]
Documentation and type correction for `options.type` available in https://github.com/PLhery/node-twitter-api-v2/releases/tag/1.5.0.
