### ISSUE TITLE
How to get DM response

### ISSUE THREAD

**Issue by gauloics** [PLhery/node-twitter-api-v2#71]
`EDirectMessageEventTypeV1` get error not defined

**Comment by alkihis** [comment]
All exposed types should be imported from module.
```ts
import { EDirectMessageEventTypeV1 } from 'twitter-api-v2'
// or
const { EDirectMessageEventTypeV1 } = require('twitter-api-v2')
```

for everything else, see the [related documentation](https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/v1.md#direct-messages-dms) and Twitter documentation.
