### ISSUE TITLE
Fix v1.tweets typing 

### ISSUE THREAD

**Issue by Zeusz0** [PLhery/node-twitter-api-v2#72]
Funtcion header of V1.tweets is:
```TwitterApiv1ReadOnly.tweets(ids: string | string[], options?: TweetLookupNoMapV1Params): Promise<UserV1[]>```

however according to the documantation should be: `Promise<TweetV1[]>` or `Promise<TweetLookupMapV1Result>`
 
https://github.com/PLhery/node-twitter-api-v2/blob/7eb6399ddba4eacb3a18c727119e539ada3b64cf/doc/v1.md#get-multiple-tweets

**Comment by alkihis** [comment]
Hello, thanks you for your report.

Type modification will be patched and published soon :)

**Comment by alkihis** [comment]
Available in 1.5.1.
