### ISSUE TITLE
Remove or Document id keys

### ISSUE THREAD

**Issue by Zeusz0** [PLhery/node-twitter-api-v2#73]
id_str does not equal to id, probably some kind of casting malfunction:

`console.log(+"1436278513418522630") ` 
`> 1436278513418522600`

It could cause some serious harm due to the problem's nature. Please fix or document it!

**Comment by alkihis** [comment]
Hello,

It is a **known and normal** behavior, documented and explained in Twitter documentation.
Twitter IDs are **64-bit integers**, causing a floating-point precision loss when JSON payloads are parsed into `number` type.

Please use `id_str` instead.
