### ISSUE TITLE
Recipe for scheduling a Twitter Thread?

### ISSUE THREAD

**Issue by deadcoder0904** [PLhery/node-twitter-api-v2#76]
There is a library https://github.com/adblanc/twit-thread/ which is built on top of `twit` that allows publishing threads.

Threads are really popular nowadays so built-in support would be great or perhaps a recipe in the helper section :)

Would love to know if this is in the Roadmap?

**Comment by PLhery** [comment]
I think it would be a good idea indeed, let's use this issue to keep track of it :)

**Comment by deadcoder0904** [comment]
Added by @alkihis in #79 → https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/v1.md#Tweetathreadoftweet

**Comment by Basharath** [comment]
How can I fetch a Twitter thread by using the tweet ID?
