### ISSUE TITLE
uploadMedia fails with buffer input

### ISSUE THREAD

**Issue by carlos-molero** [PLhery/node-twitter-api-v2#90]
Hi, I've been trying to use this wrapper for the upload media endpoint in a project and it works pretty well for local files but when I try to pass a buffer created from binary data it prompts:

`Error: Failed to process media`

This is how I get the binary data:

```javascript
const getVideoBuffer = (previewUrl: string) => {
  return new Promise((resolve, reject) => {
    request.defaults({ encoding: null });
    request.get(previewUrl!, async (error, response, body) => {
      if (error) {
        reject(new Error(`Something went wrong getting binary data from preview url ${error}`));
      }
      resolve(Buffer.from(body));
    });
  });
};

```

Here I get the buffer and start the upload:

```javascript
 const buffer: any = await getVideoBuffer(previewUrl || '');
 const mediaId = await client.v1.uploadMedia(buffer, { type: 'mp4', target: 'tweet'});
 const tweet = await client.v1.tweet('Hello!', { media_ids: mediaId });
 console.log(tweet);
```

Am I missing something?
Thanks in advance

**Comment by alkihis** [comment]
Hello,
Thanks for using our library :)

The most possible issue here is that your input video isn't supported by Twitter. 
What happens when you download the video manually in a regular file, then upload it using filepath?

Buffer upload is covered by our unit tests (with a simple `fs.readFile()` that returns a `Buffer` object) and everything goes fine.

**Comment by carlos-molero** [comment]
I will try your suggestions and comeback, thanks a lot for the quick response!

**Comment by carlos-molero** [comment]
It was the `request` package, just noticed that is deprecated. Thanks a lot @alkihis , that solved the issue.

**Comment by savannahar68** [comment]
Hey @carlos-molero, what did you use instead of request ?
Facing the exact same problem. Would appreciate if you can paste the updated code.

Thanks

**Comment by carlos-molero** [comment]
Hi @savannahar68, we just ended up using axios, here:

```javascript
const res: any = await axios.get(previewUrl || '', { responseType: 'arraybuffer' });
log.info('Content fetched...');
const buffer = res.data;
const mediaId = await client.v1.uploadMedia(buffer, { type: 'longmp4', target: 'tweet' });
```
Then you would call 

```javascript
const tweet = await client.v1.tweet("Your tweet", { media_ids: mediaId });
```

Good luck!

**Comment by savannahar68** [comment]
Thanks man @carlos-molero 👍🏻
