### ISSUE TITLE
got error id undefine

### ISSUE THREAD

**Issue by gauloics** [PLhery/node-twitter-api-v2#95]
`await client.v1.deleteWelcomeDm(welcomeDm[EDirectMessageEventTypeV1.WelcomeCreate].id);
`
How to define the id?

**Comment by bedwardly-down** [comment]
What's your code look like and what were you trying to do when it happened? There needs to be more info here for this to be a useful bug report. Thanks. :D

**Comment by gauloics** [comment]
thanks for your response,
I'm using nodejs, which runs the telegram bot, then I'm trying to create a welcome message from the telegram user input. 
To create a new welcomedm it worked, but when I want to delete I'm having problems with the definition of id

**Comment by alkihis** [comment]
Hi,

I don't know what exactly you mean by "definition of id", but using `deleteWelcomeDm` is pretty straightforward. 
You can find an example in unit tests, file `test/dm.v1.test.ts`:

```ts
import { EDirectMessageEventTypeV1 } from 'twitter-api-v2';

// Create
const createdWelcomeDm = await client.v1.newWelcomeDm('name', {
  text: 'New message text, for rule !',
});

const dmId = createdWelcomeDm[EDirectMessageEventTypeV1.WelcomeCreate].id;

// Or you can obtain via get
const welcomeMessage = await client.v1.getWelcomeDm(createdWelcomeDm);
const dmId = welcomeMessage[EDirectMessageEventTypeV1.WelcomeCreate].id;

// Or via list
const dms = await client.v1.listWelcomeDms()
for (const dm of dms) {
  const dmId = dm.id;
  // do something with dmId
}

// Yet, you have obtained an ID
await v1Client.deleteWelcomeDm(dmId);
```

**Please**, for your future issues, include a *real* code example, a meaningful issue name and (for the sake of kindness), greetings. :D 
Otherwise, I'll just close the issue immediately.

**Comment by gauloics** [comment]
@alkihis  Thank this helpfull
Can you show me how to check listWelcomeDms is empty?
