### ISSUE TITLE
KEEP GETTING TypeError: The "listener" argument must be of type Function. Received type object

### ISSUE THREAD

**Issue by ghost** [PLhery/node-twitter-api-v2#96]
Here is the code that I have written: 
`const client = new TwitterApi({
    appKey: API_KEY,
    appSecret: API_KEY_SECRET,
    accessToken: ACCESS_TOKEN,
    accessSecret: ACCESS_TOKEN_SECRET,
  })
  // const client = new TwitterApi(BEARER_TOKEN);

 async function makeTweet() {
    const createdTweet = await client.v1.tweet('twitter-api-v2 is awesome!')
    console.log('Tweet', createdTweet.id_str, ':', createdTweet.full_text)
  }
`

Is the API broken or am I making a mistake somewhere? Thanks

**Comment by alkihis** [comment]
Re,
It seems that `agent-base` dropped `https.request` patching since `5.0.0` (two years ago): https://github.com/TooTallNate/node-agent-base/issues/38#issuecomment-564212230.

Please check your (sub)dependencies, and update them.
